server:
  port: 8090

#日志配置
logging:
  config: classpath:logback.xml

#配置调度中心地址
xxl:
  job:
    admin:
      addresses: http://127.0.0.1:8001/xxl-job-admin
    #执行器和调度中心之间的通信令牌，如果没有配置，表示关闭了通信令牌的校验
    #在 xxl-job-admin 的配置文件中，有一个一模一样的配置项，两边都配置，就会进行校验。
    #accessToken:
    #配置执行器的名字
    executor:
      appname: xxl-job-sesame
      #address: #执行器地址，如果没有配置，就是用 IP:PORT 作为默认值
      #ip: #执行器 ip 地址
      port: 9999 #执行器端口，默认即9999
      logpath: ./applogs/xxl-job/jobhandler #执行器日志文件位置
      logretentiondays: 30 #执行器日志保存时间